name: Audit Terraform

on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  terraform-audit:
    name: Terraform Audit
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: dev
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::853878127117:role/github-actions-oidc-role-dev
          aws-region: us-east-1
          role-session-name: github-actions-${{ github.run_id }}

      - name: Scan Code for Secrets (Gitleaks)
        uses: gitleaks/gitleaks-action@v2

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}

      - name: IaC Audit with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform
        continue-on-error: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Setup TFLint and AWS Plugin
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.59.1

      - name: Terraform Validate & Lint
        run: |
          tflint --init
          tflint --version
          echo "Running TFLint..."
          tflint --recursive
        continue-on-error: true
      
      - name: Terraform Validate
        run: |
          terraform --version
          terraform fmt -check=true -diff=true -recursive
          terraform init -input=false -backend-config=environment/dev/state.tfvars -reconfigure
          terraform validate

  terraform-plan:
    name: Terraform Plan Dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::853878127117:role/github-actions-oidc-role-dev
          aws-region: us-east-1
          role-session-name: github-actions-${{ github.run_id }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
  
      - name: Terraform Plan
        id: plan
        run: |
          terraform init -input=false -backend-config=environment/dev/state.tfvars -reconfigure
          terraform plan -var-file=environment/dev/variables.tfvars -input=false -out=dev.tfplan
          terraform show --json dev.tfplan > dev-tfplan.json


